# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
" Define a job to be invoked later in a workflow.
#See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
Jobs
say-hello:
# Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
# Seet https://circleci.com/docs/executor.intro/ & https://circleci.com/docs/configuration-reference/#executor-job
docker:
# Specify the version you desire here
#See: https://circleci.com/developer/images/image/cing/base
- Image: cing/base:current
# Add steps to the job
# Sce: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
steps:
Checkout the code as the first step.
- checkout
- run:
name: "Say hello"
comand: "echo Hello, World!-

sonarqube:
working_directory: ~/build
docker:
- image: sonarsource/sonar-scanner-cli
resource_class: small
steps:
- run: find.
- attach_workspace:
at: ~/workspace
- run: |
SONAR_BRANCH-"$(CIRCLE_BRANCH :- master}"
echo "Sonar branch value is: " SSONAR_BRANCH
echo "Sonar org value is : "SSONAR_ORG
sonar-scanner \
-Dsonar.projectKey-"SSONAR_PROJECI_KEY" 1
-Dsonar.organization-"$SONAR_ORG"\
-Dsonar.host.url-https://sonarcloud.io \
-Dsonar.exclusions-" ** /android/ ** , ** /ios/ ** " \
-Dsonar.login-"SSONAR_TOKEN" \
-Dsonar.branch.name-"$SONAR_BRANCH" \
-Dsonar.sources-"."


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
# Inside the workflow, you define the jobs you want to run.
jobs:
- say-hello
- sonarqube
 
  

